### ISSUE TITLE
Can pru-dds send a non-repetitive, computed byte stream?

### ISSUE THREAD

**Issue by omnister** [n8vi/pru-dds#8]
I'm trying to get a double-buffered PRU setup to allow a stepper motor program to write precisely timed byte streams to an output port.  I compute all the step/dir pulses, in advance, (github.com/omnister/velo) and would like to stream them using the PRU.  It looks like your program almost does just what I want.  Do you have a ring-buffer so that the driver program can fill the PRU memory on the fly just ahead of the output pointer?  I can see that you do repetitive wavetables - for my application, I need a continuous stream.  Sorry to open an issue, I searched diligently but couldn't find any email for you in the docs.
## kind regards,

Rick Walker (walker@omnisterra.com)

**Comment by n8vi** [comment]
No problem, Rick.  Wouldn't matter, I've had email issues lately anyway.  I believe you can send a non-repetitive bytestream by basically "AM-modulating" DC.  Set your DDS frequency to zero, then AM stream.  Fill the buffer in 8KB chunks.  The only problem here is that the sample rate as designed would be 8Ksam/s.  So perhaps that doesn't work.

Alternately, there is a program to load the wavetable from a file of raw samples.  Problem here is that it doesn't interact with the interrupt system so your code doesn't know when it's time to refill half of the buffer for the next batch.

There is some half-completed code in there to double buffer output at full speed, but given the limited 8KB size of the PRU memory, I think it ran too fast for the main CPU to keep up.  I haven't experimented with slowing things down.  This stuff exists, I believe, in sam.p.  which I think you can feed with modstream.

I'll probably take a look at this soonish, because I don't think you're the first person to ask me about this.

**Comment by n8vi** [comment]
So, I guess the answer is "yes, but at lower sample rates, due to hardware constraints"
